### ISSUE TITLE
What should the instance field be in config?

### ISSUE THREAD

**Issue by gavin-hall** [jamescarlos/slackcamp#1]
define('SLACK_INSTANCE')

What should i enter for this? The full URL as https://MYSITE.slack.com/ or just MYSITE?

Thanks!

**Comment by jamescarlos** [comment]
@gavin-hall just MYSITE

**Comment by gavin-hall** [comment]
@jamescarlos Many thanks!

**Comment by jamescarlos** [comment]
@gavin-hall no problem. I have a few other minor updates I'm going to push to the repo, but for the most part it should work properly in it's current state.

**Comment by gavin-hall** [comment]
All is working nicely now
