### ISSUE TITLE
slackcamp stopped working; no idea why

### ISSUE THREAD

**Issue by lubomski** [jamescarlos/slackcamp#13]
We have been happily using slackcamp for a number of months (many thanks!). On August 10th it seemed to simply stop working. 

On some preliminary testing, it seems that slackcamp can obtain the events from basecamp (hacked in a print_r($events) to see), but there seems to be nothing being received by Slack. I've checked my network filter (Little Snitch) and it appears to be sending some encrypted info out via /usr/bin/php... I've contacted slack to see if there's been any changes at their end... not had a response yet.

Any ideas where to start looking?

**Comment by lubomski** [comment]
Resetting the clone, reconfiguring the slackcamp instance revealed a difference in the original implementation; define('slack_webhook_url'); is now used (was previously 'slack_instance_api').

**Comment by jamescarlos** [comment]
Thanks for the update @lubomski. Glad that was figured out.
