### ISSUE TITLE
Basecamp 3 removed password

### ISSUE THREAD

**Issue by heytomsmith** [jamescarlos/slackcamp#14]
[If you are new to Basecamp 3, you don't receive a password.](https://basecamp.com/help/3/guides/people/signin#if-you-never-set-up-a-password)

Setting up a config.php now using 

``` php
define('BASECAMP_PASSWORD', '');
```

and

``` php
define('BASECAMP_PASSWORD', 'NULL');
```

but neither are working.

**Comment by jamescarlos** [comment]
Hi @heytomsmith, slackcamp only works with Basecamp 2 at the moment. There has not been a Basecamp 3 API released yet.

**Comment by heytomsmith** [comment]
Ah. Thanks for the quick reply.
