### ISSUE TITLE
Is vendor/autoload.php missing?

### ISSUE THREAD

**Issue by gavin-hall** [jamescarlos/slackcamp#2]
require **DIR** . '/vendor/autoload.php';

Im getting a fail message from my MediaTemple CRON manager that its missing and i don't see in the master branch.

**Comment by jamescarlos** [comment]
@gavin-hall see the Installation instructions in the `README.md` again. Make sure you run composer in order to install the necessary libraries.
`php composer.phar install`

**Comment by gavin-hall** [comment]
Thanks installed and its not throwing an error anymore.

**Comment by jamescarlos** [comment]
@gavin-hall awesome!
