### ISSUE TITLE
Old style URL

### ISSUE THREAD

**Issue by drafie** [jamescarlos/slackcamp#7]
The URL / TOKEN structure you are using is depreciated.  

The new API uses a structure like this:

https://hooks.slack.com/services/XXXXXXX/YYYYYY/ZZZZZZZZ

You can support this by adding something like 

define('SLACK_URL'),'https://hooks.slack.com/services/XXXXXXX/YYYYYY/ZZZZZZZZ';

Then checking in slackcamp.php around like 16 to see if SLACK_URL is not empty, if not empty then set URL to that otherwise proceed with old style token.

**Comment by lukeberry99** [comment]
I've submitted a pull request that updates Slackcamp to the new structure. As far as my tests have shown the old token style method is deprecated and no longer works with Slack.
